[book]
title = "Applied Data Science"
authors = ["Gabriel Sanchez"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
additional-js = ["theme/quiz.js"]
additional-css = ["theme/quiz.css"]
